read me file
FACG5/voyage pull request #13
Opened 2018-09-10 11:12 UTC by donia98

2018-09-10 17:49 UTC, FarahZaqout requested changes
Few grammar errors.

2018-09-10 17:49 UTC, FarahZaqout commented on README.md
> +A web application that allows you to search and explore places of entertainment in Gaza and gives you the possibility to give your opinion in places after you register as a regular user on the site .
Grammar correction: Give your opinion on places

2018-09-10 17:49 UTC, FarahZaqout commented on README.md
> +If you are the owner of an entertainment site and want to market it you can register as a business account and then you can view your services and receive views of people about the services and the p
Receive reviews. (instead of receive views)

2018-09-10 17:49 UTC, FarahZaqout commented on README.md
> +People in Gaza often suffer from difficult access to suitable recreational places, for example a family that wants to go to a park and looking for the nearest one that is clean and quiet. Our site wi
our site will allow them to search for nearby parks in Gaza

2018-09-10 17:49 UTC, FarahZaqout commented on README.md
> +  - I can add a rate this place.
I can rate this place.

2018-09-12 14:25 UTC, donia98 commented
I resolved the grammar error

2018-09-12 23:03 UTC, merged