Add BE and FE without css business page Relates #6
FACG5/voyage pull request #22
Opened 2018-09-12 22:11 UTC by Asmaa-ezz

I Add 4 file in back and front end in business page 
* public/js/`business_page.js` 
* src/controllers/`business_page.js`
* src/model/`queries/review.js`
* src/views/`business_page.hbs` 

- [ ] could view all data in business 
- [ ] could view all review in this business
- [ ] used 2 button and switch between them 
- [ ] could calculate average evaluation

2018-09-12 22:11 UTC, Asmaa-ezz commented
@FarahZaqout

2018-09-13 07:43 UTC, FarahZaqout requested changes

2018-09-13 07:43 UTC, FarahZaqout commented on public/js/business_page.js
> +const getElement = id => document.getElementById(id);
document is undefined and will get you a warning from eslint.
use ```/* global document */``` at the top of the file to avoid that.

2018-09-13 07:43 UTC, FarahZaqout commented on src/controllers/business_page.js
> +        .catch(err => res.render('business_page', {
Error handling should be done using its own middleware.
Use the ```next``` parameter to handle errors.

2018-09-13 11:24 UTC, FarahZaqout approved these changes

2018-09-13 11:24 UTC, merged