Categories style Relate #12
FACG5/voyage pull request #26
Opened 2018-09-13 13:41 UTC by donia98

- Add style for categories button in the home page 'mobile first design'.
- Add style for the category page.

2018-09-14 09:20 UTC, asmaa-ezz approved these changes

2018-09-14 19:02 UTC, AsalaKM approved these changes

2018-09-15 08:28 UTC, FarahZaqout approved these changes

2018-09-15 08:31 UTC, FarahZaqout requested changes
Too many files changed. Most of them are unrelated to the branch itself.

2018-09-15 08:31 UTC, FarahZaqout commented on src/model/database/db_build.sql
> +INSERT INTO users (email, password, type) VALUES ('asmaa@gmail.com', '000', 'person');
No sql commands are allowed in the build file.

2018-09-16 08:30 UTC, FarahZaqout approved these changes

2018-09-16 08:31 UTC, merged