Reviews
FACG5/voyage pull request #27
Opened 2018-09-13 14:03 UTC by AsalaKM

**Back-End**
-view the reviews .
-view comments that related to reviews.

**Front-End**
-Adding contact-us page and view the contact form with front end validations.
-Adding about us page.
-Editing some styles.

2018-09-14 09:20 UTC, asmaa-ezz approved these changes

2018-09-15 08:34 UTC, FarahZaqout requested changes
Pull request is titled reviews, yet it has a lot of files unrelated to reviews.

2018-09-15 08:34 UTC, FarahZaqout commented on public/js/home.js
> +// buttonComment.addEventListener('click', () => {
Remove commented code.

2018-09-15 08:34 UTC, FarahZaqout commented on src/model/database/db_build.sql
> +INSERT INTO users (email, password, type) VALUES ('asmaa@gmail.com', '000', 'person');
No sql commands allowed in build.sql file.

2018-09-16 11:08 UTC, FarahZaqout requested changes

2018-09-16 11:08 UTC, FarahZaqout commented on package.json
> +<<<<<<< HEAD
This is an unresolved conflict.

Use travis.

2018-09-16 11:30 UTC, donia98 approved these changes

2018-09-16 11:42 UTC, FarahZaqout requested changes

2018-09-16 11:42 UTC, FarahZaqout commented on public/js/contact_us.js
> +  // alert('Thanks For Your Sending');
This function does nothing.

2018-09-16 11:42 UTC, FarahZaqout commented on src/views/partials/head.hbs
> +<<<<<<< HEAD
Unresolved conflict.

2018-09-16 11:42 UTC, FarahZaqout commented on src/views/contact_us.hbs
> +							<div class="contact-form">
this is too much indentation. Make sure no eslint warnings are in your files.

2018-09-16 11:45 UTC, FarahZaqout requested changes
Make sure no eslint warnings are up.

2018-09-16 11:45 UTC, FarahZaqout commented on .travis.yml
> +- node
add new line at the end of your files.

2018-09-16 11:45 UTC, FarahZaqout commented on public/css/about_us.css
> +}
add new line.

2018-09-16 11:45 UTC, FarahZaqout commented on public/css/contact_us.css
> +}
add new line

2018-09-16 12:03 UTC, FarahZaqout approved these changes

2018-09-16 12:03 UTC, merged