Profile
FACG5/voyage pull request #32
Opened 2018-09-17 13:47 UTC by AsalaKM

**User Profile**
Show user information and all reviews that related to the user.

2018-09-17 13:57 UTC, AsalaKM commented
Relates #5

2018-09-18 06:36 UTC, FarahZaqout requested changes

2018-09-18 06:36 UTC, FarahZaqout commented on public/js/home.js
> +/* global window */
these two lines can be one.
```/* global document window */```

2018-09-18 06:36 UTC, FarahZaqout commented on src/controllers/user_profile.js
> +        const { gender, username } = response[0];
```username``` is already declared in the upperscope. You should not shadow it or modify it.

2018-09-18 06:36 UTC, FarahZaqout commented on public/js/home.js
> +/* global window */
also use global fetch

2018-09-18 06:36 UTC, FarahZaqout commented on public/js/home.js
> +/* global window */
and global alert.

btw alert is generally considered a bad practice. The function alert is regarded as bad user experience, and is generally used in development for debugging purposes. You should use other methods in future projects. You don't need to change the alert now, this is just information to keep in mind in  your next project.

2018-09-18 07:28 UTC, FarahZaqout requested changes

2018-09-18 07:28 UTC, FarahZaqout commented on public/js/business_page.js
> +  if (evaluation.textContent >= 1) {
Using switch should be a lot cleaner.

2018-09-18 07:28 UTC, FarahZaqout commented on src/model/database/db_build.sql
> +INSERT INTO users (email, password, type) VALUES ('asmaa@gmail.com', '000', 'person');
No inserts in build.sql

2018-09-18 09:08 UTC, FarahZaqout approved these changes

2018-09-18 09:08 UTC, merged