Somestyle
FACG5/voyage pull request #46
Opened 2018-09-19 12:56 UTC by Asmaa-ezz

Style for aignUp and aboutUs pages

2018-09-19 13:05 UTC, AsalaKM approved these changes

2018-09-19 13:31 UTC, FarahZaqout commented
Change the name of the branch and the pull request.

Take your commits seriously. They're extremely important for remote teams and larger projects.

2018-09-19 13:32 UTC, FarahZaqout requested changes
Name your commits and branches proeprly.

use url-friendly naming in future branches.

2018-09-20 02:49 UTC, FarahZaqout approved these changes
read the issue about how to write commits.

2018-09-20 07:15 UTC, merged