Supertest
FACG5/voyage pull request #47
Opened 2018-09-19 13:48 UTC by donia98

2018-09-21 07:03 UTC, FarahZaqout requested changes

2018-09-21 07:03 UTC, FarahZaqout commented on package.json
> +    "dbtest": "NODE_ENV=test tape test/test.js | tap-spec",
this script will fail. The file is ```test_db```, not ```test```.

2018-09-21 19:49 UTC, donia98 commented on package.json
> +    "dbtest": "NODE_ENV=test tape test/test.js | tap-spec",
I solved it. could you approve the pull request or marge it?

2018-09-22 13:19 UTC, FarahZaqout approved these changes

2018-09-22 13:19 UTC, FarahZaqout commented on src/controllers/sign_in.js
> -        res.send({ err: 'invalid username or password' });
The removed message was the proper one. Length is < 0 will only confuse the user.

2018-09-22 13:19 UTC, FarahZaqout commented on src/middlewares/checkauth.js
> +  if (req.cookies) {
req.cookies will always be true. This line is unnecessary.

2018-09-22 20:23 UTC, merged